# name of the software
name: Sikker Digital Post .NET
# current version of the software
version: 1.2.5540.26013
# url of the download button
downloadUrl: https://github.com/mistic100/jekyll-bootstrap-doc
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/sikker-digital-post-net-klient" # the subpath of your site, e.g. /blog/

collections:
  doks:
    output: true

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/difi/sikker-digital-post-net-klient

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/difi/sikker-digital-post-net-klient
  - title: Issues
    url: https://github.com/difi/sikker-digital-post-net-klient/issues

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# github buttons
githubButton:
  user: difi
  repo: sikker-digital-post-net-klient

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  account:
  domain:

# DON'T MODIFY
highlight: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
