########################################################
##               MASTER and BETA BUILD                ##
########################################################
- 
  branches:
    only:
      - master
      - beta
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    strong_name_signingkey_secret:
      secure: bjxsFmbUwz8FwDx9d6dqR1q+kVdZ7JGbKKShVrAIRIs=
    virksomhetssertifikat_secret:
      secure: bjxsFmbUwz8FwDx9d6dqR1q+kVdZ7JGbKKShVrAIRIs=
    virksomhetssertifikat_pass:
      secure: 1GZYP7hef/X/3sNeNpGukg==
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt signingkey.snk.enc -secret %strong_name_signingkey_secret%
    - secure-file\tools\secure-file -decrypt bring.p12.enc -secret %virksomhetssertifikat_secret%
  before_build:
  - ps: >-
      .\appveyor-deploy\InstallVirksomhetssertifikat.ps1 -virksomhetssertifikat bring.p12;
      .\appveyor-deploy\MoveSigningKey.ps1 -signingKeyPath "$env:APPVEYOR_BUILD_FOLDER\signingkey.snk" -signingKeyDestination "C:\Keys\signingkey.snk";
      .\appveyor-deploy\NugetRestore.ps1;
      .\appveyor-deploy\AssemblyInfoVersionPatcher.ps1 -assemblyInfoPath  ".\SolutionItems\SharedAssemblyInfo.cs"; 
      .\appveyor-deploy\BuildPreamble.ps1   
  build:
    verbosity: minimal  
  after_build:
  - ps: >-
      .\appveyor-deploy\NuspecVersionPatcher.ps1 -assembly "Difi.SikkerDigitalPost.Klient\bin\Release\Difi.SikkerDigitalPost.Klient.dll" -nuspec "difi-sikker-digital-post-klient.nuspec";
      nuget pack;
  artifacts:
    - path: '*.nupkg'
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1
  before_deploy:
  - ps: >-
      .\appveyor-deploy\DeployPreamble.ps1
  deploy:
    provider: NuGet
    api_key:
      secure: 0XDZbOBgkBlfSxTEu3A3uDCYrmw0ICpdHpfPt6slFJraBECbX29LKxItKKtEFiMy
    skip_symbols: true
    artifact: /.*\.nupkg/


########################################################
##                    OTHER BRANCHES                  ##
########################################################

-
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    strong_name_signingkey_secret:
      secure: klTrmUGElJ32M1IvA5ecksVOZoUhA22ZAEVhpi5qaZY=
    virksomhetssertifikat_secret:
      secure: bjxsFmbUwz8FwDx9d6dqR1q+kVdZ7JGbKKShVrAIRIs=
    virksomhetssertifikat_pass:
      secure: 1GZYP7hef/X/3sNeNpGukg==  
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt signingkey.snk.enc -secret %strong_name_signingkey_secret%
    - secure-file\tools\secure-file -decrypt bring.p12.enc -secret %virksomhetssertifikat_secret%
  before_build:
  - ps: >-
      .\appveyor-deploy\InstallVirksomhetssertifikat.ps1 -virksomhetssertifikat bring.p12;
      .\appveyor-deploy\MoveSigningKey.ps1 -signingKeyPath "$env:APPVEYOR_BUILD_FOLDER\signingkey.snk" -signingKeyDestination "C:\Keys\signingkey.snk";
      .\appveyor-deploy\NugetRestore.ps1;
      .\appveyor-deploy\BuildPreamble.ps1          
  build:
    verbosity: minimal  
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1
